import { useDashboard } from '../app/dashboard-context';
import { EnergyTrendChart, NetEnergyChart } from '../components/charts/EnergyTrendChart';
import { SERIES } from '../components/charts/chart-theme';
import { ProducerRanking } from '../components/households/HouseholdRankings';
import { useHouseholdDetail } from '../components/households/use-household-detail';
import { BigStat, Card, Help, Section } from '../components/ui/layout';
import { Loaded } from '../components/ui/Loaded';
import type { Decimal } from '../types/api';
import {
  formatCount,
  formatDateTime,
  groupDigits,
  isNegative,
  isZero,
  toChartNumber,
} from '../utils/format';

/** How much energy the neighbourhood produced and used, when, and who produced it. */
export function EnergyPage() {
  const { period, data, timeWindow, refreshToken } = useDashboard();
  const detail = useHouseholdDetail();
  const bucket = timeWindow.bucket;

  return (
    <>
      <Section
        title="Energy balance"
        description={`${period}, from every meter reading the smart meter service received.`}
      >
        <Card>
          <Loaded resource={data.energy} what="energy statistics" height={120}>
            {({ summary }) => (
              <div className="space-y-6">
                <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
                  <BigStat
                    label="Produced"
                    accent={SERIES.production}
                    help="Energy generated by the households' solar panels, as their meters reported it."
                    value={groupDigits(summary.productionKwh)}
                    unit="kWh"
                  />
                  <BigStat
                    label="Used"
                    accent={SERIES.consumption}
                    help="Energy the households used, as their meters reported it."
                    value={groupDigits(summary.consumptionKwh)}
                    unit="kWh"
                  />
                  <BigStat
                    label="Net energy"
                    accent={SERIES.net}
                    help="Produced minus used. Above zero, more was produced than used."
                    value={groupDigits(summary.netKwh)}
                    unit="kWh"
                    caption={
                      isZero(summary.netKwh)
                        ? 'As much produced as used.'
                        : isNegative(summary.netKwh)
                          ? 'More used than produced.'
                          : 'More produced than used.'
                    }
                  />
                </div>
                <dl className="grid grid-cols-2 gap-4 border-t border-line pt-4 sm:grid-cols-4">
                  <Fact label="Households reporting" value={formatCount(summary.households)} />
                  <Fact label="Meter readings" value={formatCount(summary.readings)} />
                  <Fact label="First reading" value={formatDateTime(summary.firstReadingAt)} />
                  <Fact label="Latest reading" value={formatDateTime(summary.lastReadingAt)} />
                </dl>
              </div>
            )}
          </Loaded>
        </Card>
      </Section>

      <Section
        title="Production and use over time"
        description={`Energy produced and used per ${bucket}, in kWh. Hover or tap a point for exact figures.`}
      >
        <Card>
          <Loaded resource={data.energy} what="energy over time" height={320}>
            {({ trend }) => <EnergyTrendChart trend={trend} />}
          </Loaded>
        </Card>
      </Section>

      <Section
        title="Net energy over time"
        description={`Produced minus used, per ${bucket}. Bars above zero: more produced than used. Bars below zero: more used than produced.`}
      >
        <Card>
          <Loaded resource={data.energy} what="net energy over time" height={240}>
            {({ trend }) => <NetEnergyChart trend={trend} />}
          </Loaded>
        </Card>
      </Section>

      <Section
        title="Spare energy and demand"
        description="What households had left over, what they were short of, and how much of it changed hands."
      >
        <Card>
          <Loaded resource={data.energy} what="energy statistics" height={120}>
            {({ summary }) => (
              <SupplyDemand
                spare={summary.surplusKwh}
                needed={summary.demandKwh}
                traded={data.market.data?.summary.completed.energyKwh ?? null}
                tradedUnavailable={data.market.status === 'error'}
              />
            )}
          </Loaded>
        </Card>
      </Section>

      <Section
        title="By household"
        description="The households whose panels generated the most energy in the period."
      >
        <ProducerRanking
          timeWindow={timeWindow}
          refreshToken={refreshToken}
          onSelect={detail.open}
        />
      </Section>
      {detail.drawer}
    </>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className="min-w-0">
      <dt className="text-[13px] text-ink-3">{label}</dt>
      <dd className="mt-0.5 text-[15px] font-medium text-ink">{value}</dd>
    </div>
  );
}

/**
 * Three amounts of energy on one scale: spare, needed and traded. All kWh, so
 * the bars compare directly; each also carries its exact figure.
 */
function SupplyDemand({
  spare,
  needed,
  traded,
  tradedUnavailable,
}: {
  spare: Decimal;
  needed: Decimal;
  traded: Decimal | null;
  tradedUnavailable: boolean;
}) {
  const rows = [
    {
      label: 'Spare energy',
      help: 'For every reading where a household produced more than it used, the difference - added up. This is what could be offered to neighbours.',
      value: spare,
      color: SERIES.production,
    },
    {
      label: 'Energy needed',
      help: 'For every reading where a household used more than it produced, the shortfall - added up.',
      value: needed,
      color: SERIES.consumption,
    },
    {
      label: 'Traded and settled',
      help: 'Energy sold from one household to another in trades billing has recorded. From the trade matching service.',
      value: traded,
      color: SERIES.traded,
    },
  ];
  const longest = Math.max(0, ...rows.map((row) => toChartNumber(row.value) ?? 0));

  return (
    <ul className="space-y-4">
      {rows.map((row) => {
        const amount = toChartNumber(row.value);
        const width = amount !== null && longest > 0 ? (amount / longest) * 100 : 0;
        return (
          <li key={row.label}>
            <div className="flex flex-wrap items-baseline justify-between gap-2 text-[13px]">
              <span className="flex items-center gap-1.5 font-medium text-ink-2">
                <span
                  aria-hidden="true"
                  className="h-2.5 w-2.5 rounded-sm"
                  style={{ background: row.color }}
                />
                {row.label}
                <Help term={row.label}>{row.help}</Help>
              </span>
              <span className="text-[15px] font-semibold text-ink">
                {row.value === null ? (
                  <span className="text-[13px] font-normal text-ink-3">
                    {tradedUnavailable
                      ? 'Not available: trade statistics could not be loaded'
                      : 'Loading…'}
                  </span>
                ) : (
                  <>
                    {groupDigits(row.value)}{' '}
                    <span className="text-[13px] font-normal text-ink-3">kWh</span>
                  </>
                )}
              </span>
            </div>
            <div
              aria-hidden="true"
              className="mt-1.5 h-3 w-full overflow-hidden rounded-sm bg-raised"
            >
              {width > 0 ? (
                <div
                  className="h-full rounded-sm"
                  style={{ width: `${width}%`, background: row.color }}
                />
              ) : null}
            </div>
          </li>
        );
      })}
    </ul>
  );
}
