import type { ReactNode } from 'react';
import type { EnergySection, MarketSection } from '../../hooks/use-dashboard-data';
import type { Resource } from '../../hooks/use-resource';
import { formatCount, groupDigits, isNegative, isZero } from '../../utils/format';
import { SERIES } from '../charts/chart-theme';
import { BigStat } from '../ui/layout';
import { cx, Skeleton } from '../ui/primitives';

/**
 * The four numbers the grid is about - made, used, the difference, and what
 * changed hands - each with a sentence saying what it is, for the period in
 * view. Straight from the services' summaries.
 */
export function GridOverview({
  period,
  energy,
  market,
}: {
  period: string;
  energy: Resource<EnergySection>;
  market: Resource<MarketSection>;
}) {
  const e = energy.data?.summary;
  const m = market.data?.summary;

  return (
    <section
      aria-labelledby="grid-overview-title"
      className="min-w-0 rounded-lg border border-line bg-surface"
    >
      <div className="flex flex-wrap items-baseline justify-between gap-2 border-b border-line px-5 py-3">
        <h2 id="grid-overview-title" className="text-[15px] font-semibold text-ink">
          Grid overview
        </h2>
        <p className="text-[13px] text-ink-3">{period}</p>
      </div>
      <div className="grid grid-cols-1 divide-y divide-line sm:grid-cols-2 sm:divide-y-0 xl:grid-cols-4">
        <Cell resource={energy} name="production" border="sm:border-b sm:border-r xl:border-b-0">
          <BigStat
            label="Produced"
            accent={SERIES.production}
            help="Energy generated by the households' solar panels, as their meters reported it."
            value={groupDigits(e?.productionKwh)}
            unit="kWh"
            caption="Energy generated by household solar panels in this period."
          />
        </Cell>
        <Cell resource={energy} name="consumption" border="sm:border-b xl:border-b-0 xl:border-r">
          <BigStat
            label="Used"
            accent={SERIES.consumption}
            help="Energy the households used, as their meters reported it."
            value={groupDigits(e?.consumptionKwh)}
            unit="kWh"
            caption="Energy the households used in this period."
          />
        </Cell>
        <Cell resource={energy} name="net energy" border="sm:border-r">
          <BigStat
            label="Net energy"
            accent={SERIES.net}
            help="Produced minus used. Above zero the neighbourhood made more than it needed; below zero it needed more than it made."
            value={groupDigits(e?.netKwh)}
            unit="kWh"
            caption={e ? <NetMeaning net={e.netKwh} /> : null}
          />
        </Cell>
        <Cell resource={market} name="traded energy">
          <BigStat
            label="Traded"
            accent={SERIES.traded}
            help="Energy one household sold to another through the market, where the sale has been billed and recorded."
            value={groupDigits(m?.completed.energyKwh)}
            unit="kWh"
            caption={
              m
                ? `Sold between neighbours and settled, in ${formatCount(m.trades.completed)} ${m.trades.completed === 1 ? 'trade' : 'trades'}.`
                : null
            }
          />
        </Cell>
      </div>
    </section>
  );
}

function NetMeaning({ net }: { net: string }) {
  const [word, detail] = isZero(net)
    ? ['Balanced', 'as much produced as used']
    : isNegative(net)
      ? ['Short', 'more used than produced']
      : ['Surplus', 'more produced than used'];
  return (
    <>
      <span className="font-medium text-ink-2">{word}:</span> {detail}. Produced minus used.
    </>
  );
}

function Cell<T>({
  resource,
  name,
  border,
  children,
}: {
  resource: Resource<T>;
  name: string;
  border?: string;
  children: ReactNode;
}) {
  return (
    <div
      className={cx('min-w-0 border-line px-5 py-5', border)}
      aria-busy={resource.status === 'loading' || resource.refreshing || undefined}
    >
      {resource.status === 'loading' ? (
        <div className="space-y-3">
          <Skeleton className="h-4 w-24" />
          <Skeleton className="h-9 w-36" />
          <Skeleton className="h-3 w-48" />
          <span className="sr-only">Loading {name}</span>
        </div>
      ) : resource.status === 'error' ? (
        <div>
          <p className="text-[13px] font-medium text-ink-2">
            {name[0]!.toUpperCase() + name.slice(1)}
          </p>
          <p className="mt-2 text-lg font-semibold text-ink-2">Not available</p>
          <p className="mt-1 text-[13px] text-ink-3">{resource.error?.message}</p>
        </div>
      ) : (
        <div className={cx('transition-opacity', resource.refreshing && 'opacity-60')}>
          {children}
        </div>
      )}
    </div>
  );
}
